// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSlugifyController from "./auto_slugify_controller"
application.register("auto-slugify", AutoSlugifyController)

import CategoriesController from "./categories_controller"
application.register("categories", CategoriesController)

import ColourDiffController from "./colour_diff_controller"
application.register("colour-diff", ColourDiffController)

import DocumentMetaController from "./document_meta_controller"
application.register("document-meta", DocumentMetaController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ImageBlocksController from "./image_blocks_controller"
application.register("image-blocks", ImageBlocksController)

import NestedFormsController from "./nested_forms_controller"
application.register("nested-forms", NestedFormsController)
