# spec/factories/categories.rb
FactoryBot.define do
  factory :category do
    name { Faker::Lorem.unique.word.capitalize }
    # Slug will be generated by a callback in the model, or use a derived one for testing:
    sequence(:slug) { |n| "#{name.parameterize}-#{n}" }
  end
end
