# spec/factories/tags.rb
FactoryBot.define do
  factory :tag do
    sequence(:name) { |n| "Tag Name #{n} #{Faker::Lorem.unique.word}" }
    # Slug will be generated by a callback in the model, or use a derived one for testing:
  end
end
