# spec/factories/tags.rb
FactoryBot.define do
  factory :tag do
    name { Faker::Lorem.unique.word.downcase }
    # Slug will be generated by a callback in the model, or use a derived one for testing:
    sequence(:slug) { |n| "#{name.parameterize}-#{n}" }
  end
end
