# Load Factory Bot definitions
# Needed when running seeds outside of test environment
require "factory_bot_rails"
# FactoryBot.find_definitions

# Populates the dev database with initial data
# @todo: Add the catalogue models

puts "Seeding development database..."

[
  AureliusPress::User.name,
  AureliusPress::Document::Document.namespaced_types,
  AureliusPress::Fragment::Fragment.namespaced_types,
  AureliusPress::ContentBlock::ContentBlock.name,
  AureliusPress::Taxonomy::Category.name,
  AureliusPress::Taxonomy::Tag.name,
  AureliusPress::Community::Like.name,
].flatten.each do |type|
  Object.const_get(type).destroy_all
end

puts "Cleared existing data."

docs = %i[
  aurelius_press_document_atomic_blog_post
  aurelius_press_document_blog_post
  aurelius_press_document_page
]

users_array = []

users_data = [
  {
    first_name: "Paul",
    last_name: "Devanney",
    email: "pauldevanney92@gmail.com",
    role: :superuser,
  },
  {
    first_name: "Yvonne",
    last_name: "Amores-Cabrera",
    email: "yvonne.amores-cabrera@gmail.com",
    role: :admin,
  },
  {
    first_name: "Test",
    last_name: "User",
    email: "test.user@example.com",
    role: :moderator,
  },
  {
    first_name: "Bebe",
    last_name: "Rexha",
    email: "bebe.rexha@gmail.com",
    role: :moderator,
  },
  {
    first_name: "Becky",
    last_name: "Hill",
    email: "becky.hill@gmail.com",
    role: :moderator,
  },
  {
    first_name: "Dua",
    last_name: "Lipa",
    email: "dua.lipa@gmail.com",
    role: :reader,
  },
  {
    first_name: "Miley",
    last_name: "Cyrus",
    email: "miley.cyrus@gmail.com",
    role: :superuser,
  },
  {
    first_name: "Anna",
    last_name: "Montana",
    email: "anna.montana@gmail.com",
    role: :reader,
  },
]

5.times do
  users_data << {
    first_name: Faker::Name.first_name,
    last_name: Faker::Name.last_name,
    email: Faker::Internet.email,
    role: [:reader, :user, :moderator, :admin, :superuser].sample,
  }
end

users_data.each do |user_data|
  users_array << FactoryBot.create(
    :aurelius_press_user,
    first_name: user_data[:first_name],
    last_name: user_data[:last_name],
    email: user_data[:email],
    role: user_data[:role],
    password: "password",
    password_confirmation: "password",
  )
end

puts "#{users_array.count} users created."
puts users_array.map { |u| "#{u.full_name} (#{u.role})" }.join(",\n")

################################################################################

status_trait = [:draft, :published, :archived]
puts "Creating Categories"
categories = [
  "Stoic Philosophy",
  "Stoic Practices",
  "Stoic Texts",
  "Stoic History",
  "Stoic Community",
  "Stoic Resources",
  "Stoic Events",
].map do |name|
  FactoryBot.create(:aurelius_press_taxonomy_category, name: name)
end
puts "Generated:\n#{categories.map(&:name).join(",\n")}.\n"

puts "Creating documents with belt and braces. So, prepare for a cascade \nof users generated by the factories via comments, notes etc.\n"

5.times do
  user = users_array.sample
  puts "Create doc for #{user.full_name}"
  FactoryBot.create(
    docs.sample,
    :with_belt_and_braces,
    user: user,
    category: categories.sample,
  )
  user = users_array.sample
  puts "Create doc for #{user.full_name}"
  FactoryBot.create(
    %i[
      aurelius_press_document_blog_post
      aurelius_press_document_page
    ].sample,
    :with_one_of_each_content_block,
    status_trait.sample,
    user: user,
    category: categories.sample,
  )
end

puts "Database seeding complete!"
